'use strict';
// Operational geometry is a planning aid; unknown machine dimensions are not certified clearances.
function segmentDistance(a,b,p){const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz||1)));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dz);}
function segmentPolygonDistance(a,b,poly){if(Norms.pointInPolygon&& (Norms.pointInPolygon({x:a[0],z:a[1]},poly)||Norms.pointInPolygon({x:b[0],z:b[1]},poly)))return 0;let min=Infinity;for(let i=0;i<poly.length;i++){const c=[poly[i].x,poly[i].z],d=[poly[(i+1)%poly.length].x,poly[(i+1)%poly.length].z];if(segmentCrossPoint(a,b,c,d))return 0;min=Math.min(min,segmentDistance(a,b,c),segmentDistance(a,b,d),segmentDistance(c,d,a),segmentDistance(c,d,b));}return min;}
function operationalObstacles(){const list=CONFIG.objects.filter(o=>!['well','septic','canopy'].includes(o.id)).map(o=>({id:o.id,object:o}));const can=Norms.obj('canopy');if(can)for(const [i,p] of Norms.bodyCorners(can).entries())list.push({id:'canopy-post-'+i,object:{x:p.x,z:p.z,w:.16,d:.16,rot:0}});LANDSCAPE_PLAN.containers.forEach(p=>list.push({id:p.id,object:p}));list.push({id:'trash',object:FRONT_SERVICE_PLAN.trash});return list;}
function corridorAudit(points,width,excluded=[]){const found=[];const obstacles=operationalObstacles().filter(o=>!excluded.includes(o.id));for(let i=1;i<points.length;i++)for(const item of obstacles){const o=item.object;let distance;if(o.radius!=null)distance=segmentDistance(points[i-1],points[i],[o.x,o.z])-o.radius;else distance=segmentPolygonDistance(points[i-1],points[i],Norms.bodyCorners({...o,rot:o.rot||0}));if(distance<width/2-.015)found.push({segment:i,objectId:item.id,clearance:+distance.toFixed(3),required:width/2,status:'needs-review'});}return found;}
function vehicleAudit(){const v=BernV6.project.vehicle,width=v.width??1.9,length=v.length??4.7,points=[-3,2,6].map(z=>[14.5,z]);const collisions=[];for(const [i,p] of points.entries()){const vehicle={x:p[0],z:p[1],w:width,d:length,rot:0};for(const item of operationalObstacles().filter(o=>o.id!=='car'))if(Norms.dist(vehicle,item.object)<-.01)collisions.push({position:i,objectId:item.id});}if(width>FRONT_SERVICE_PLAN.gate.opening)collisions.push({position:'gate',objectId:'gate-opening'});return {dimensionsKnown:v.width!=null&&v.length!=null,width,length,collisions,method:'Три позиции + прямой коридор; без кинематической симуляции',corridor:corridorAudit([[14.5,-5],[14.5,8.5]],width,['car'])};}
const originalOperationAudit=operationAudit;
operationAudit=function(){const result=originalOperationAudit();const width=BernV6.project.snowBlowerWidth??.65;result.snowConflicts=corridorAudit(snowBlowerRoute(),width,['shed','house']);result.vehicle=vehicleAudit();result.assumedSnowWidth=BernV6.project.snowBlowerWidth==null;result.issues.push(...[...new Set(result.snowConflicts.map(c=>c.objectId))].map(id=>'Снегоуборщик: проверить конфликт с '+id));result.issues.push(...[...new Set([...result.vehicle.collisions,...result.vehicle.corridor].map(c=>c.objectId))].map(id=>'Въезд: проверить конфликт с '+id));return result;};
function fenceOccluders(){if(!appState.fenceShadows)return [];const H=currentFenceDimensions(),f=FRONT_SERVICE_PLAN,g=gateGeometry();const out=[];const box=(a,b,h)=>out.push({ownId:'fence',box:new THREE.Box3(new THREE.Vector3(Math.min(a[0],b[0])-.03,0,Math.min(a[1],b[1])-.03),new THREE.Vector3(Math.max(a[0],b[0])+.03,h,Math.max(a[1],b[1])+.03))});box([0,0],[f.wicket.start,0],H.frontHeight);box([g.end,0],[CONFIG.plot.w,0],H.frontHeight);box([f.wicket.start,0],[f.wicket.start+f.wicket.width,0],H.frontHeight);const shift=appState.gateOpen?f.gate.opening:0;box([g.start+shift,.17],[g.end+shift,.17],H.frontHeight);for(const [a,b] of [[[0,0],[0,CONFIG.plot.d]],[[CONFIG.plot.w,0],[CONFIG.plot.w,CONFIG.plot.d]],[[0,CONFIG.plot.d],[CONFIG.plot.w,CONFIG.plot.d]]])box(a,b,H.neighborHeight);return out;}
BernV6.fenceOccluders=fenceOccluders;
